# Generated by Django 4.2.6 on 2023-11-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photos',
            new_name='profile_photo',
        ),
    ]
